services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "9432:5432"
  web:
    stdin_open: true
    tty: true
    build: .
    command: python mysite/manage.py runserver 0.0.0.0:8654
    volumes:
      - .:/code
    ports:
      - "8654:8654"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db


